import { StyleSheet } from "react-native";

export default StyleSheet.create({
    homeContainer: {
        flex: 1,
    },
    scrollView: {
        flex: 1,
        backgroundColor: '#f5f5f5',
        width: '100%',
    },
    container: {
        alignItems: 'center',
        padding: 20,
        paddingTop: 40,
        flex: 1,
    },
    content: {
        flexGrow: 1,
        alignItems: 'center',
        padding: 20,
        paddingTop: 40,
        paddingBottom: 150,
    },
    titulo: {
        fontSize: 18,
        color: '#666',
        marginBottom: 10,
    },
    saldo: {
        fontSize: 42,
        fontWeight: 'bold',
        marginBottom: 30,
    },
    positivo: {
        color: '#2ecc71',
    },
    negativo: {
        color: '#e74c3c',
    },
    resumoContainer: {
        flexDirection: 'row',
        gap: 15,
        marginTop: 20,
        marginBottom: 30,
    },
    card: {
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 10,
        minWidth: 150,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    cardTitulo: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    valorReceita: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#2ecc71',
    },
    valorDespesa: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#e74c3c',
    },
    transacoesContainer: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
        flex: 1,
    },
    transacoesScroll: {
        flex: 1,
    },
    transacoesTitulo: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 15,
    },
    transacaoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    transacaoInfo: {
        flex: 1,
    },
    transacaoNome: {
        fontSize: 16,
        color: '#333',
        fontWeight: 'bold',
        marginBottom: 4,
    },
    transacaoDescricao: {
        fontSize: 14,
        color: '#666',
        fontWeight: '400',
    },
    transacaoData: {
        fontSize: 12,
        color: '#999',
    },
    transacaoValor: {
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 10,
    },
    transacoesPageWrapper: {
        flex: 1,
        padding: 20,
        backgroundColor: '#f5f5f5',
    },
    transacoesPageTitulo: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 20,
    },
    addTransacaoButton: {
        backgroundColor: '#00490e',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 3,
    },
    addTransacaoButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    transacoesListWrapper: {
        flex: 1,
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 15,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    tabBar: {
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        height: 70,
        paddingBottom: 10,
        paddingTop: 10,
    },
    tabBarLabel: {
        fontSize: 12,
        fontWeight: '600',
        marginTop: 4,
    },
    tabBarIcon: {
        marginTop: 5,
    },
    tabIcon: {
        fontSize: 20,
    },
    valorPositivo: {
        color: '#2ecc71',
    },
    valorNegativo: {
        color: '#e74c3c',
    },
    mensagemVazia: {
        textAlign: 'center',
        color: '#999',
        fontSize: 14,
        marginTop: 10,
    },
    page: {
        flex: 1,
        backgroundColor: '#f5f5f5',
        alignItems: 'center',
        flexDirection: 'column',
    },
    button: {
        padding: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: '5%',
        borderRadius: 10,
        marginRight: '5%',
        backgroundColor: '#81cc2a',
    },
    text1: {
        color: '#f1f1f1',
    },
    text2: {
        color: '#1d1c1cff',
    },
    posButton: {
        marginTop: '2%',
        marginLeft: 'auto',
        marginRight: '5%',
    },

    // Estilos para o formulário AddEdit
    formContainer: {
        width: '90%',
        maxWidth: 500,
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 30,
        marginTop: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    formTitulo: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 30,
        textAlign: 'center',
    },
    inputContainer: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
        fontWeight: '500',
    },
    input: {
        backgroundColor: '#f5f5f5',
        borderRadius: 8,
        padding: 15,
        fontSize: 16,
        color: '#333',
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    inputFocused: {
        borderColor: '#00490e',
        backgroundColor: '#fff',
    },
    tipoContainer: {
        flexDirection: 'row',
        gap: 15,
        marginBottom: 20,
    },
    tipoButton: {
        flex: 1,
        padding: 15,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#e0e0e0',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    tipoButtonSelected: {
        borderColor: '#00490e',
        backgroundColor: '#f0f8f0',
    },
    tipoButtonReceita: {
        borderColor: '#2ecc71',
        backgroundColor: '#e8f8f0',
    },
    tipoButtonDespesa: {
        borderColor: '#e74c3c',
        backgroundColor: '#fdeaea',
    },
    tipoText: {
        fontSize: 16,
        color: '#666',
        fontWeight: '500',
    },
    tipoTextSelected: {
        color: '#00490e',
        fontWeight: 'bold',
    },
    tipoTextReceita: {
        color: '#2ecc71',
        fontWeight: 'bold',
    },
    tipoTextDespesa: {
        color: '#e74c3c',
        fontWeight: 'bold',
    },
    submitButton: {
        backgroundColor: '#00490e',
        padding: 18,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 3,
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    cancelButton: {
        backgroundColor: 'transparent',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: 10,
        borderWidth: 2,
        borderColor: '#e0e0e0',
    },
    cancelButtonText: {
        color: '#666',
        fontSize: 16,
        fontWeight: '500',
    },

    top: {
        topo: {
            marginTop: 0,
            backgroundColor: '#00490e',
            width: '100%',
            flexDirection: 'row',
            alignItems: 'center',
        },
        topoImg: {
            width:150,
            height: 150,
            marginLeft: 'auto',
            marginRight: 'auto',
        },
        topoTexto: {
            fontSize: 20,
            color: '#f1f1f1',
            marginLeft: 10,
        },
        menu: {
            flexDirection: 'row',
            marginLeft: 'auto',
            marginRight: '5%',
        },
        textMenu: {
            padding: 10,
            borderRadius: 10,
        },
        textoMenuSelect: {
            backgroundColor: '#bded85',
            color: '#00490e',
        },
    },

    verFin: {
        view: {
            width: '100%',
            height: '75%',
        },
        views: {
            marginLeft: 'auto',
            marginRight: 'auto',
            marginTop: '2%',
            flexDirection: 'column',
            alignItems: 'center',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.1,
            shadowRadius: 3.84,
            elevation: 5,
            padding: 10,
            width: '30%',
            borderRadius: 10,
            backgroundColor: '#ffffff',
        },
        buttons: {
            marginTop: '2%',
            flexDirection: 'row',
        },
        buttonEdit: {
            padding: 10,
            alignItems: 'center',
            justifyContent: 'center',
            marginRight: '5%',
            borderRadius: 5,
            marginLeft: 'auto',
            backgroundColor: '#ffc145',
        },
        buttonDelete: {
            padding: 10,
            alignItems: 'center',
            justifyContent: 'center',
            marginLeft: '5%',
            borderRadius: 5,
            marginRight: 'auto',
            backgroundColor: '#b80c09',
        },
        viewValores:{
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            width: '100%',
        },
        text: {
            fontSize: 20,
            marginRight: '2%',
        },
        val: {
            fontSize: 30,
            marginLeft: '2%',
        },
        textDesc: {
            color: '#1d1c1c64',
        },
    },
})